# Result

- Rust では、例外はなくエラーが発生する箇所では明示的にエラーを呼び出し元に返却する必要がある
- エラー伝播には「?」を使って中身を取り出したり、エラー時に呼び出し元に返却したりできる
